#!/bin/bash

YUMUTILS='yum-utils device-mapper-persistent-data lvm2'
REPO='https://download.docker.com/linux/centos/docker-ce.repo'

echo " removing old docker"
sudo yum -y remove docker 
sudo yum -y remove docker-common 
sudo yum -y remove docker-selinux 
sudo yum -y remove docker-engine

sudo yum install -y $YUMUTILS


echo " adding docker Repo"
sudo yum-config-manager --add-repo $REPO
sudo yum-config-manager --enable docker-ce-edge
sudo yum-config-manager --enable docker-ce-test
sudo yum -y install docker-ce

sudo systemctl start docker
sudo systemctl enable docker

echo " adding other utils"
sudo yum -y install vim
sudo yum -y install git

echo " installing docker-compose"
sudo yum -y install epel-release
sudo yum -y install python-pip
sudo pip install docker-compose
sudo yum upgrade python* -y


echo -e " enabling docker swarm" && sudo docker swarm init --advertise-addr 192.168.200.22

echo -e " installing docker machine"
sudo curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && sudo install /tmp/docker-machine /usr/bin/docker-machine

echo -e " installing VBox"
sudo cd /etc/yum.repos.d/
sudo yum install -y wget
sudo wget http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
sudo yum --enablerepo=epel install dkms
sudo yum groupinstall "Development Tools" -y
sudo yum search VirtualBox
sudo yum install VirtualBox-5.2.x86_64 -y


echo -e " the mandatory start of everything"
sudo docker run hello-world
